#!/sbin/openrc-run
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="rtl_ais"
description="A simple AIS tuner and generic dual-frequency FM demodulator"
supervisor=supervise-daemon
healthcheck_timer=5
command=/usr/bin/rtl_ais
command_args="${RTL_AIS_ARGS}"
command_backgroud=true
pidfile=/var/run/rtl_ais.pid

depend() {
  need net
  use logger
}
