#!/sbin/openrc-run
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="signalk-server-node"
description="SignalK Node Server"
command=/opt/signalk-server-node/bin/signalk-server
command_args="${SIGNALK_SERVER_ARGS}"
command_background=true
pidfile=/var/run/signalk-server-node.pid

depend() {
  need net
  use logger
}

start_pre() {
  checkpath -f -o signalk:signalk -m 0775 \
    ${logfile}
}
